//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Binboo.Jira {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Binboo_Jira {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Binboo_Jira() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Binboo.Jira.Binboo.Jira", typeof(Binboo_Jira).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigns one (or more) issue(s) to a specific developer
        ///
        ///use: %cmd% &lt;issue-list&gt; &lt;main developer&gt;| myself [&lt;peer&gt;| myself] [&lt;iteration&gt;].
        /// </summary>
        internal static string Assign {
            get {
                return ResourceManager.GetString("Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the sum of IDS for the Early Progress Report.
        ///
        ///Use: %cmd% [*all|open|closed].
        /// </summary>
        internal static string CountIDS {
            get {
                return ResourceManager.GetString("CountIDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop the task for the current iteration by reseting assignee/peer/iteration in the correspondent ticket.
        ///
        ///Use: %cmd% &lt;issue-list&gt; [&lt;comment&gt;]
        ///Sample:%cmd% ISSUE-1, ISSUE-2, ISSUE-3  &quot;Have to play video game :)&quot;.
        /// </summary>
        internal static string Drop {
            get {
                return ResourceManager.GetString("Drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets issue&apos;s estimation in IDS
        ///
        ///Use:%cmd% &lt;issue-list&gt; &lt;estimation&gt;.
        /// </summary>
        internal static string Estimate {
            get {
                return ResourceManager.GetString("Estimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files a new issue into jira system. 
        ///
        ///Use: %cmd% &lt;project&gt; &lt;summary&gt; [description] [&lt;order&gt;] [type=*bug|task|improvement].
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help
        ///
        ///Use: %cmd% [&lt;command&gt;].
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the main details about an issue
        ///
        ///Use: %cmd% &lt;issue-list&gt; [comments]
        ///Sample: %cmd% ISSUE-1, ISSUE-2, ISSUE-3.
        /// </summary>
        internal static string Issue {
            get {
                return ResourceManager.GetString("Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add, removes or lists labels for one or more issues
        ///
        ///Use: %cmd% &lt;issue-list&gt; [+label] [-label1]
        ///Sample:%cmd%  ISSUE-1, ISSUE2 +foo -bar (adds label foo and removes label bar for the specified issues).
        /// </summary>
        internal static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links issues
        ///
        ///Use: %cmd% &lt;ticket#&gt; link-type &lt;tiket#&gt;.
        /// </summary>
        internal static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays a list of all projects registered in Jira.
        ///
        ///Use: %cmd%.
        /// </summary>
        internal static string ListProjects {
            get {
                return ResourceManager.GetString("ListProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose pairs randomically.
        /// </summary>
        internal static string Pairs {
            get {
                return ResourceManager.GetString("Pairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks issues as resolved.
        ///
        ///Use: %cmd% &lt;ticket #&gt;  fixed|won&apos;t fix|incomplete|cannot reproduce  [versions=v1, v2, ..., vn] [comment].
        /// </summary>
        internal static string Resolve {
            get {
                return ResourceManager.GetString("Resolve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searchs for issues containing the text.
        ///Use:%cmd% text [all|*open|closed].
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the order for one or more issues
        ///
        ///Use: %cmd% &lt;issue-list&gt; order
        ///Sample:%cmd% ISSUE-1, ISSUE2 3.
        /// </summary>
        internal static string SetOrder {
            get {
                return ResourceManager.GetString("SetOrder", resourceCulture);
            }
        }
    }
}
